#!/usr/bin/env bash
#script that will display information about subdomains

domain="$1"
sub_domain="$2"


dns_lookup() {
    dig "$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print "The subdomain","'"$host_name"'","is a",$4,"record and points to",$5}'

}

if [ "$domain" ] && [ "$sub_domain" ]; then
    host_name="$sub_domain.$domain"
    dns_lookup "$host_name"
    

elif [ "$domain" ]; then
    subdomains=(www lb-01 web-01 web-02)
    for subdomain in "${subdomains[@]}" ; do
        host_name="$subdomain.$domain"
        dns_lookup "$host_name"
    done
fi
